### ISSUE TITLE
Add (cross-cluster) search

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#13]
We should add a search view that searches for objects across clusters.
This search should have filters to specify e.g. kinds of objects, namespaces, clusters, etc.

**Acceptance Criteria:**
- [ ] The search should be accessible from any view within a cluster.
- [ ] It should allow to filter what the search refers to (object kinds, namespaces, etc.), and what cluster to search in (or all, when omitted).
- [ ] It should show the results with links to their respective detailed views.

**Comment by lijianzhi01** [comment]
I think it is useful for cases of searching pod and deployment. We are planning to add this in next year. 
My problem is what happens if I search in 100 clusters. Is it slow.

**Comment by illume** [comment]
> I think it is useful for cases of searching pod and deployment. We are planning to add this in next year. My problem is what happens if I search in 100 clusters. Is it slow.

Yeah, this is a problem was identified again in a recent review of our search on youtube.

It's also a problem if there are 200 users with a single large cluster since that will hammer the API server into the ground.
