### ISSUE TITLE
Create a desktop app

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#22]
Some users prefer to use a dashboard from their machines instead of having it running in a cluster or hosted somewhere else.

To support this use-case, we should have a desktop application (Electron) for the most used platforms: Linux, Mac, Windows.

**Acceptance Criteria:**
- [x] A Headlamp desktop app exists for Linux
- [x] A Headlamp desktop app exists for Mac
- [x] A Headlamp desktop app exists for Windows

**Comment by ashu8912** [comment]
This has landed in master we can close it now @joaquimrocha

**Comment by joaquimrocha** [comment]
Not yet. We need to build + upload the executables.
