### ISSUE TITLE
Design revamp / Add logo

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#25]
The overall design of the dashboard will be reviewed by a designer, so we make sure the UX and UI great for our users. We also need a nice logo.

**Acceptance Criteria:**
- [x] The UI/UX of the main parts has been reviewed, changes have been implemented (more details TBD)
- [x] The project has a logo and it's being used in the UI
- [x] The project has a logo and it's being used in the README
